In [1]:
a = 2.4455
round(a,2)

2.45

In [4]:
#imp
a = 1627731
round(a, -2)  #minus refers to the decimal places

1627700

In [5]:
#Dont confuse rounding with formatting a value for output. If your goal is simply to output a numerical value with a ceratin number of decimal places, you dont typically need to use round()

x = 1.23232
format(x, '0.2f')

'1.23'

Performing Accurate Decimal Calculations



In [6]:
from decimal import Decimal

Decimal(x)

Decimal('1.232320000000000081996631706715561449527740478515625')

In [7]:
a = Decimal('4.2')
b = Decimal('2.1')
a+b

Decimal('6.3')

In [9]:
#Decimal can also be used in other contexts also

from decimal import Decimal, localcontext

a = Decimal('4.3')
b = Decimal('5.6')

print(a/b)
with localcontext() as ctx:
    ctx.prec = 4
    print(a/b)

0.7678571428571428571428571429
0.7679


In [10]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a/b)

0.76785714285714285714285714285714285714285714285714


In [11]:
#Formatting numbers


x = 1234.56789

In [12]:
format(x, '0.2f')

'1234.57'

In [16]:
for i in (format(x,'<10.2f'), format(x, '>10.1f'), format(x,',')):
    print(i)

1234.57   
    1234.6
1,234.56789


In [20]:
#If you want to use exponential notation, change the f to an e or E

format(x, '0.2e')

'1.23e+03'

In [21]:
#one can also swap the separators


swap_separators = {ord('.'):',', ord(','):'.'}

In [24]:
format(x,',').translate(swap_separators)

'1.234,56789'

In [26]:
'%10.2f'%x   #10 gaps and upto two decimal places

'   1234.57'

Working with Binary, Octal, and Hexadecimal
Integers


In [28]:
#To convert an integer into a binary, octal or hexadecimal text string use the bin(), oct(), or hex() functions,respectively:

x = 1234

bin(x),oct(x),hex(x)


('0b10011010010', '0o2322', '0x4d2')

In [29]:
#alternatively

format(x, 'b'),format(x,'o'),format(x,'x')

('10011010010', '2322', '4d2')

In [31]:
#WORD OF CAUTION

import os
os.chmod('script.py', 0o755)

FileNotFoundError: [Errno 2] No such file or directory: 'script.py'

Packing and Unpacking Large Integers from Bytes

In [32]:
#You have a byte string and you need to unpack it into an integer value,
#ALternatively you need to convert a large integer back into a byte string

In [33]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [37]:
len(data)

16

In [38]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [39]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

In [40]:
#Discussion
#Converting large integer values to and from byte strings is not a common operation. However it sometimes arises in certain application domains, such as cryptography or networking. For instance, IPv6 network addresses are represented as 128 bit integers. If youare writing code that needs to pull such values out of a data record, you might face this problem

In [41]:
#As an alternative to this recipem you might be inclined to unpack values using the struct module, as described. This works, but the size of integers that can be unpacked with struct is limited. Thus you would need to unpack multiple values and combine them to create the final value. For example:

data

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [42]:
import struct

hi, lo = struct.unpack('>QQ', data)
(hi << 64) + lo

94522842520747284487117727783387188

In [43]:
x = 0x01020304

In [44]:
x.to_bytes(4, 'big')


b'\x01\x02\x03\x04'

In [45]:
x.to_bytes(4, 'little')

b'\x04\x03\x02\x01'

In [ ]:
#If you try to pack an integer into a byte string, but it wont fit, you will get an error. You can use the 
int.bit_length()

In [48]:
x = 523 ** 23

x

335381300113661875107536852714019056160355655333978849017944067

In [ ]:
x.to_bytes(16, 'little')

In [50]:
x.bit_length()

208

In [51]:
nbytes, rem = divmod(x.bit_length(), 8)

In [52]:
nbytes, rem

(26, 0)

In [53]:
if rem:
    nbytes += 1

In [54]:
x.to_bytes(nbytes, 'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

Performing Complex-Valued Math

In [55]:
#Your code for interacting with thelatest web authentication scheme has encountered a singularity and your only solution is to go around it in the complex plane. Or maybe you just need to perform some calculations using complex numbers.

In [60]:
#Complex numbers can be specified using the complex(real, imag) function or by floating point numbers with a j suffix

a = complex(2,4)
b  = 3 - 5j  #floating point numbers can also be depicted by j suffix

In [64]:
a.imag, a.real, a.conjugate()

(4.0, 2.0, (2-4j))

In [65]:
a + b

(5-1j)

In [66]:
a - b

(-1+9j)

In [67]:
a/b

(-0.4117647058823529+0.6470588235294118j)

In [69]:
abs(a)

4.47213595499958

In [70]:
#To perform additional complex valued functions such as sines, cosines or square roots use the cmath module:

import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218173j)

In [71]:
cmath.cos(a), cmath.exp(a)

((-11.36423470640106-24.814651485634183j),
 (-4.829809383269385-5.5920560936409816j))

Discussion

In [75]:
#Most of pythons math related modules are aware of complex values. For example if you use numpy, it is straightforward to make arrays of complex values and perform operations on them:

import numpy as np

a = np.array([2+3j, 4+5j, 6-7j, 8+9j])

In [76]:
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [77]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [ ]:
import math
math.sqrt(-1)

In [79]:
#if you want want complex numbers produced as a result you have to explicityly use cmath

import cmath

cmath.sqrt(-1)

1j

Working with Infinity and NaNs

In [81]:
a  = float('inf')

Calculating with Fractions

In [86]:
from fractions import Fraction

a = Fraction(5,4)
b = Fraction(5,6)
a/b
print(a/b)

3/2


In [87]:
#Getting Numerator/denominator

c = a*b
c.numerator


25

In [88]:

c.denominator

24

In [89]:
#limiting the denominator of a value

print(c.limit_denominator(8))

1


In [90]:
#converting float to fraction

x = 3.75
y  = Fraction(x)

In [91]:
print(y)

15/4


Calculating with Large Numerical Arrays

In [92]:
#You need to perform calculations on large numerical datasets, such as arrays or grids.

In [95]:
x = [1,2,3,4]
np.array(x)

array([1, 2, 3, 4])

In [96]:
#Numpy arrays
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])

In [97]:
ax * 2

array([2, 4, 6, 8])

In [98]:
ax + 10

array([11, 12, 13, 14])

In [99]:
ax + ay

array([ 6,  8, 10, 12])

In [102]:
#if we want to use particularly the in built array and multiply by something then

def ar_mul(array):
    return [i*2 for i in array]

In [103]:
ar_mul(x)

[2, 4, 6, 8]

In [104]:
#instead numpy provides a collection of universal functions that alos allow for array operations 

np.sqrt(ar_mul(x))

array([1.41421356, 2.        , 2.44948974, 2.82842712])

In [105]:
#prefer inbuilt functions or thirdparty functions over loops

grid = np.zeros(shape = (1000,1000), dtype=float)

In [106]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [122]:
grid += 10

In [123]:
grid[:1] += np.random.rand()

In [133]:
grid.reshape(-1,5).shape

(200000, 5)

In [149]:
def grid_mod(grid):
    i = 0
    while(i<len(grid)):
        grid[i:(i+1)] += np.random.randint(1,2)
        i+=1
    return grid

In [150]:
grid1 = grid_mod(grid=grid)

In [151]:
grid1

array([[14.2205119 , 14.2205119 , 14.2205119 , ..., 14.2205119 ,
        14.2205119 , 14.2205119 ],
       [14.11819445, 14.11819445, 14.11819445, ..., 14.11819445,
        14.11819445, 14.11819445],
       [13.75143369, 13.75143369, 13.75143369, ..., 13.75143369,
        13.75143369, 13.75143369],
       ...,
       [13.23426667, 13.23426667, 13.23426667, ..., 13.23426667,
        13.23426667, 13.23426667],
       [13.23214757, 13.23214757, 13.23214757, ..., 13.23214757,
        13.23214757, 13.23214757],
       [14.29420634, 14.29420634, 14.29420634, ..., 14.29420634,
        14.29420634, 14.29420634]])

In [152]:
np.where(grid1>13,a,10)

array([[Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)],
       [Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)],
       [Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)],
       ...,
       [Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)],
       [Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)],
       [Fraction(5, 4), Fraction(5, 4), Fraction(5, 4), ...,
        Fraction(5, 4), Fraction(5, 4), Fraction(5, 4)]], dtype=object)

Performing Matrix and Linear Algebra Calculations

In [153]:
import numpy as np
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [154]:
#transpose of a matrix
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [155]:
#inverse of a matrix

m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [156]:
#create a vector and multiply

v = np.matrix([[2],[3],[4]])
v

matrix([[2],
        [3],
        [4]])

In [157]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [159]:
#More operations can be found in the numpy.linalg subpackage

import numpy.linalg

#Determinant
np.linalg.det(m)

-229.99999999999983

In [160]:
np.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [161]:
#solve for x in mx = v

x = np.linalg.solve(m,v)
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

Picking Things at Random

In [163]:
#The random module has various functions for random numbers and picking random items.

import random

values = [1,2,3,4,5]
random.choice(values)

1

In [171]:
random.choice(values)   #This is to pick a random item out of a sequence use random.choice()

5

In [173]:
#To take a sampling of n items where selected items are removed from further considereation use random.sample() instead:

random.sample(values, 1)

[1]

In [174]:
#You can also shuffle the values

np.random.shuffle(values)

In [175]:
values

[3, 4, 1, 2, 5]

In [176]:
#To produce uniform floating point values in the range 0 to 1 use random.random()

random.random()

0.034560124576801465

In [178]:
#To get n random bits expressed as an integer use random.getrandbits

random.getrandbits(29)

199886949

The random module computes random numbers using the Mersenne Twister algorithm.

In [179]:
random.seed()

In [180]:
random.seed(12345)

In [181]:
random.seed(b'bytedata')

Converting Days to Seconds, and Other Basic Time
Conversions

In [184]:
from datetime import timedelta
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)

c = a + b
c.days

2

In [185]:
c.seconds

37800

In [186]:
c.seconds/3600

10.5

In [188]:
c.total_seconds()

210600.0

In [189]:
#If you need to represent specific dates and times, create datetime instances and use the standard mathematical operations to manipulate them


from datetime import datetime
a = datetime(2012, 9, 23)
print(a + timedelta(days=10))

2012-10-03 00:00:00


In [190]:
b = datetime(2012, 12, 21)

In [191]:
d = b - a

In [192]:
d.days

89

In [199]:
now = datetime.today()

In [200]:
print(now)

2023-01-28 00:49:23.022053


In [201]:
print(now + timedelta(minutes=50))

2023-01-28 01:39:23.022053


In [ ]:
#Also to note that the datetime module is aware of leap years.

In [4]:
from datetime import datetime, timedelta

a = datetime(2019, 9, 23)

In [6]:
a + timedelta(months=1)  #wrong way

TypeError: __new__() got an unexpected keyword argument 'months'

In [8]:
#correct way
from dateutil.relativedelta import relativedelta
a  + relativedelta(months=+1)

datetime.datetime(2019, 10, 23, 0, 0)

In [9]:
a + relativedelta(months=+4)

datetime.datetime(2020, 1, 23, 0, 0)

In [10]:
#Time between two dates

b  = datetime(2012, 12, 21)

In [11]:
d = b- a

In [12]:
d

datetime.timedelta(days=-2467)

Determining Last Friday's Date

In [13]:
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
'Friday', 'Saturday', 'Sunday']

In [15]:
def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

In [16]:
datetime.today()

datetime.datetime(2023, 1, 28, 18, 13, 37, 579109)

In [17]:
get_previous_byday('Monday')

datetime.datetime(2023, 1, 23, 18, 13, 44, 337013)

In [18]:
datetime.today().weekday()

5

In [19]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import *

d = datetime.now()

In [20]:
print(d)

2023-01-28 18:15:22.868034


In [21]:
#Next Friday
print(d + relativedelta(weekday=FR))

2023-02-03 18:15:22.868034


In [22]:
#Last Friday
print(d + relativedelta(weekday=FR(-1)))

2023-01-27 18:15:22.868034


Finding the Date Range for the Current Month

In [23]:
#You have some code that needs to loop over each date in the current month, and want an efficient way to calculate that date range

In [25]:
from datetime import datetime, date, timedelta
import calendar

def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
        _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
        end_date = start_date + timedelta(days=days_in_month)
        return (start_date, end_date)

In [ ]:
a_day = timedelta(days=1)
first_day, last_day = get_month_range()
while first_day<last_day:
    print(first_day)
    first_day+=a_day

In [29]:
#Ideally it would be nice to create a function that works like the built in range() function but for dates, Fortunately this is extremely easy to implement using a generator

def date_range(start, stop, step):
    while start<stop:
        yield start
        start += step

In [33]:
for d in date_range(datetime(2019,11,2), datetime(2020,12,1), timedelta(days=30)):
    print(d)

2019-11-02 00:00:00
2019-12-02 00:00:00
2020-01-01 00:00:00
2020-01-31 00:00:00
2020-03-01 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-30 00:00:00
2020-06-29 00:00:00
2020-07-29 00:00:00
2020-08-28 00:00:00
2020-09-27 00:00:00
2020-10-27 00:00:00
2020-11-26 00:00:00


Converting Strings into Datetimes

In [34]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()

diff = z - y
diff


datetime.timedelta(days=3782, seconds=66704, microseconds=14930)

In [41]:
z = datetime(2013, 3, 23)
datetime.strftime(z, '%A|%B %C %Y')

'Saturday|March 20 2013'

In [42]:
from datetime import datetime

def parse_ymb(s):
    year_s, month_s, day_s = s.split('/')
    return datetime(int(year_s), int(month_s), int(day_s))

In [43]:
parse_ymb('2019/02/23')

datetime.datetime(2019, 2, 23, 0, 0)

Manipulating Dates Involving Time Zones

In [45]:
from datetime import datetime
from pytz import timezone


d = datetime(2012,12,21,9,30,0)
print(d)

2012-12-21 09:30:00


In [46]:
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

2012-12-21 09:30:00-06:00


In [47]:
#Once the date has beeen localized it can be converted to other time zone


bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))

In [48]:
print(bang_d)

2012-12-21 21:00:00+05:30


In [52]:
d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)
later = loc_d + timedelta(minutes=30)
print(later)

2013-03-10 01:45:00-06:00
2013-03-10 02:15:00-06:00


In [53]:
#The answer is wrong because it doesnt account for the one hour skip in the local time.

from datetime import timedelta
later = central.normalize(loc_d + timedelta(minutes=30))
print(later)

2013-03-10 03:15:00-05:00


In [54]:
#To find the country timezone we can say

pytz.country_timezones['IN']

NameError: name 'pytz' is not defined